volumes:
    node_modules:
    build:
    pgdata:
services:
    frontend:
        image: node:22-alpine
        environment:
            POSTGRES_HOST: backend
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app/
            - node_modules:/home/node/app/node_modules
            - build:/home/node/app_build
        ports:
            - $FRONTEND_PORT:3000
        command: >
            sh -c "
            npm i &&
            npx prisma migrate deploy &&
            npm run build &&
            cp -t ./build/prod/client/_app/immutable/workers \
            ./node_modules/pyodide/pyodide.asm.js \
            ./node_modules/pyodide/pyodide.asm.wasm \
            ./node_modules/pyodide/python_stdlib.zip \
            ./node_modules/pyodide/pyodide-lock.json &&
            ORIGIN=$FRONTEND_ORIGIN node ./prod-server.js"
        depends_on:
            - backend

    backend:
        image: postgres:16.3-alpine
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
        volumes:
            - pgdata:/var/lib/postgresql/data
        expose:
            - $POSTGRES_PORT
