# Use this file in conjunction with docker-compose.yml to run the development environment with
# `docker compose -f docker-compose.yml -f docker-compose.dev.yml up`.

# By doing so, you:
# - Run the frontend in development mode with hot reloading
# - Expose the postgres database to the host machine for debugging purposes

# You can also run just the backend service with:
# `docker compose -f docker-compose.yml -f docker-compose.dev.yml up backend`
# if you want to run the frontend on your host machine.

services:
    frontend:
        ports:
            - 5173:5173
            - 5555:5555
        environment:
            NODE_ENV: development
        command: >
            sh -c "
            npm i &&
            npx prisma migrate deploy &&
            npx prisma generate &&
            npx prisma studio &
            npm run dev --env-file=.env -- --host"
    backend:
        ports:
            - $POSTGRES_PORT:$POSTGRES_PORT
