volumes:
    node_modules:
    build:
services:
    frontend:
        image: node:22-alpine
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app/
            - node_modules:/home/node/app/node_modules
            - build:/home/node/app_build
        ports:
            - $FRONTEND_PORT:3000
        command: >
            sh -c "
            npm i -D &&
            npm run build &&
            cp -t ./build/prod/client/_app/immutable/chunks \
            ./node_modules/pyodide/pyodide.asm.js \
            ./node_modules/pyodide/pyodide.asm.wasm \
            ./node_modules/pyodide/python_stdlib.zip \
            ./node_modules/pyodide/pyodide-lock.json &&
            node build/prod"
        depends_on:
            - backend

    backend:
        image: postgres:16.3-alpine
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
        expose:
            - 5432
